CREATE TABLE `dtakologs` (
	`__type` text NOT NULL,
	`AddressDispC` text,
	`AddressDispP` text,
	`AllState` text,
	`AllStateEx` text,
	`AllStateFontColor` text,
	`AllStateFontColorIndex` integer NOT NULL,
	`AllStateRyoutColor` text NOT NULL,
	`BranchCD` integer NOT NULL,
	`BranchName` text NOT NULL,
	`ComuDateTime` text,
	`CurrentWorkCD` integer NOT NULL,
	`CurrentWorkName` text,
	`DataDateTime` text DEFAULT '20/1/1 00:00',
	`DataFilterType` integer NOT NULL,
	`DispFlag` integer NOT NULL,
	`DriverCD` integer NOT NULL,
	`DriverName` text,
	`EventVal` text,
	`GPSDirection` integer NOT NULL,
	`GPSEnable` integer NOT NULL,
	`GPSLatiAndLong` text,
	`GPSLatitude` integer NOT NULL,
	`GPSLongitude` integer NOT NULL,
	`GPSSatelliteNum` integer NOT NULL,
	`ODOMeter` text,
	`OperationState` integer NOT NULL,
	`ReciveEventType` integer NOT NULL,
	`RecivePacketType` integer NOT NULL,
	`ReciveTypeColorName` text,
	`ReciveTypeName` text,
	`ReciveWorkCD` integer NOT NULL,
	`Revo` integer NOT NULL,
	`SettingTemp` text NOT NULL,
	`SettingTemp1` text NOT NULL,
	`SettingTemp3` text NOT NULL,
	`SettingTemp4` text NOT NULL,
	`Speed` real NOT NULL,
	`StartWorkDateTime` text,
	`State` text,
	`State1` text,
	`State2` text,
	`State3` text,
	`StateFlag` text NOT NULL,
	`SubDriverCD` integer NOT NULL,
	`Temp1` text,
	`Temp2` text,
	`Temp3` text,
	`Temp4` text,
	`TempState` integer NOT NULL,
	`VehicleCD` integer NOT NULL,
	`VehicleIconColor` text,
	`VehicleIconLabelForDatetime` text,
	`VehicleIconLabelForDriver` text,
	`VehicleIconLabelForVehicle` text,
	`VehicleName` text NOT NULL,
	PRIMARY KEY(`DataDateTime`, `VehicleCD`)
);
